In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
df = pd.read_csv("../data/churn-bigml.csv")
df_cluster = df.drop("Churn", axis=1)
df_cluster = pd.get_dummies(df_cluster, drop_first=True)

scaler = StandardScaler()
X = scaler.fit_transform(df_cluster)

kmeans = KMeans(n_clusters=4, random_state=42)
df['Cluster'] = kmeans.fit_predict(X)
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,Cluster
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,...,29.89,215.8,90,9.71,8.7,4,2.35,1,False,0
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,...,19.42,208.8,111,9.40,12.7,6,3.43,4,True,0
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,...,27.01,160.6,128,7.23,5.4,9,1.46,4,True,2
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,...,11.67,189.6,105,8.53,7.7,6,2.08,2,False,1
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,...,18.28,178.7,90,8.04,11.1,1,3.00,1,False,3

In [4]:
cluster_summary = df.groupby("Cluster").mean(numeric_only=True)
cluster_summary

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
Cluster,,,,,,,,,,,,,,,,,
0,104.000000,434.325103,8.510288,181.889712,99.292181,30.921893,211.823457,98.687243,18.004979,157.972016,98.251029,7.108560,11.576132,4.526749,3.126296,1.757202,0.119342
1,98.341232,436.137441,11.829384,134.109953,100.933649,22.799147,203.261611,98.037915,17.277204,226.251185,98.914692,10.181422,9.355450,4.175355,2.526682,1.563981,0.099526
2,105.916667,438.000000,4.950980,227.788235,102.426471,38.724657,193.803922,105.264706,16.473578,221.111765,103.431373,9.950343,9.570098,4.921569,2.584167,1.372549,0.215686
3,107.333333,444.333333,3.777778,191.911111,111.666667,32.625556,193.411111,97.444444,16.440000,217.455556,103.333333,9.785556,9.966667,3.888889,2.692222,0.666667,0.111111

In [5]:
df['Cluster'].value_counts()

Cluster
0    243
1    211
2    204
3      9
Name: count, dtype: int64

In [ ]:
df.groupby("Cluster")[['Total day minutes','Total eve minutes','Total night minutes']].mean()
df.groupby("Cluster")[['Total day charge','Total eve charge','Total night charge']].mean()
df.groupby("Cluster")['Customer service calls'].mean()
pd.crosstab(df['Cluster'], df['International plan'])

International plan   No  Yes
Cluster
0                   215   28
1                   199   12
2                   191   13
3                     9    0

In [10]:
pd.crosstab(df['Cluster'], df['State'])
pd.crosstab(df['Cluster'], df['Area code'])

Area code  408  415  510
Cluster
0           62  127   54
1           55  105   51
2           49  102   53
3            3    3    3

In [ ]:

cluster_labels = {
    0: "High-Value Premium Customers",
    1: "Budget Occasional Users",
    2: "High-Frequency Low-Spenders",
    3: "At-Risk / Churn-Prone Customers"
}

df['Customer_Type'] = df['Cluster'].map(cluster_labels)
df[['Cluster','Customer_Type']].head()

   Cluster                    Customer_Type
0        0     High-Value Premium Customers
1        0     High-Value Premium Customers
2        2      High-Frequency Low-Spenders
3        1          Budget Occasional Users
4        3  At-Risk / Churn-Prone Customers